apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-test.fullname" . }}
  labels:
    {{- include "service-test.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
#    - port: 8080
#      targetPort: http
#      protocol: TCP
#      name: http1
  selector:
    {{- include "service-test.selectorLabels" . | nindent 4 }}
